import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/app-layer/provider/provider";

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
      >
        <Provider >
        {children}
        </Provider>
      </body>
    </html>
  );
}

export default RootLayout